db.shortliterature.insert({MOVI: "12 Angry Men (1957)"})
db.shortliterature.insert({MOVI: "Forrest Gump (1994)", NOVL: {Author: "Groom, Winston.", Title: "Forrest Gump."}})
db.shortliterature.insert({MOVI: "Jurassic Park (1993)", BOOK: {Author: "Shay, Don & Duncan, Jody.", Title: "The Making of Jurassic Park."}, NOVL: {Author: "Crichton, Michael.", Title: "Jurassic Park."}})
db.shortliterature.insert({MOVI: "Se7en (1995)", ADPT: {Author: "Bruno, Anthony.", Title: "Seven (Novelization of the screenplay by Andrew Kevin Walker)."}})
db.shortliterature.insert({MOVI: "The Departed (2006)"})
db.shortliterature.insert({MOVI: "Rear Window (1954)", BOOK: {Author: "Sharff, Stefan.", Title: "The Art of Looking."}, NOVL: {Author: "Woolrich, Cornell.", Title: "It Had to Be Murder."}})
db.shortliterature.insert({MOVI: "To Kill a Mockingbird (1962)", NOVL: {Author: "Lee, Harper.", Title: "To Kill a Mockingbird."}})
db.shortliterature.insert({MOVI: "2001: A Space Odyssey (1968)", ADPT: {Author: "Clarke, Arthur C..", Title: "2001: A Space Odyssey."}})
db.shortliterature.insert({MOVI: "A Christmas Story (1983)", NOVL: {Author: "Shepherd, Jean.", Title: "In God We Trust, All Others Pay Cash."}})
db.shortliterature.insert({MOVI: "The Sixth Sense (1999)", ADPT: {Author: "Lerangis, Peter.", Title: "The Sixth Sense (Novelization of the screenplay by M. Night Shyamalan)."}})
